# Report Agent: turns findings and evidence into a structured user-facing summary report.
from __future__ import annotations

import uuid
from typing import Any

from app.agents.state import AgentState
from app.core.logger import get_logger
from app.core.model_provider import get_llm

logger = get_logger("agents.report")


def run(state: AgentState) -> dict[str, Any]:
    """
    Generates a structured summary report from the pipeline's findings and evidence.
    Uses the LLM to write a human-readable summary of the analysis results.

    ── MODEL INJECTION POINT ────────────────────────────────────────────────
    The report summary is generated by the configured LLM (default: GPT-4o).
    Set OPENAI_API_KEY in .env. Until then, a deterministic template is used.
    ─────────────────────────────────────────────────────────────────────────
    """
    findings = state.get("findings", [])
    evidence = state.get("evidence", [])
    query_text = state.get("query_text", "")
    query_id = state.get("query_id", "unknown")
    uncertainty_flag = state.get("uncertainty_flag", False)

    llm = get_llm()

    # Build summary via LLM
    findings_summary = "\n".join(
        f"- [{f.get('workflow')}] {f.get('answer') or f.get('label')} (confidence: {f.get('confidence', 0):.2f})"
        for f in findings
    ) or "No findings were generated."

    prompt = f"""You are the SatQuery AI report writer. Generate a concise, professional analysis report.

User query: {query_text}
Findings:
{findings_summary}
{'⚠️  WARNING: One or more results have low confidence. Do NOT present as certain.' if uncertainty_flag else ''}

Write a 2-3 paragraph plain-English summary that:
1. Directly answers the user's query.
2. Cites the key findings with their confidence levels.
3. Acknowledges any uncertainty clearly.
Do not make up facts not present in the findings."""

    try:
        response = llm.invoke(prompt)
        summary = response.content if hasattr(response, "content") else str(response)
    except Exception as exc:
        logger.warning("report_llm_failed", error=str(exc))
        summary = f"Analysis complete. Query: '{query_text}'. Findings: {findings_summary}"

    report_data = {
        "report_id": uuid.uuid4().hex,
        "query_id": query_id,
        "summary": summary,
        "evidence": evidence,
        "findings": findings,
        "uncertainty_flag": uncertainty_flag,
    }
    logger.info("report_generated", query_id=query_id, finding_count=len(findings))
    return {"status": "ok", "findings": [], "report": report_data}
